# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- script: 
    cat README
    ehco '1111111111111111111111111111'
    cat README
    ehco '222222222222222'
    cat README
    echo '33333333333333333333'
    cat README
    cat README
    cat README
    echo '444444444444444444444444'
    cat README
    cat README
    cat README
    cat README
    echo '55555555555555555555555555555'
    cat README
    cat README
    cat README
    cat README
    echo '6666666666666666666666666666666666666'
    cat README
    cat README
    echo '7777777777777777777777777777777777777777777'
    cat README
    cat README
    cat README
    cat README
    cat README
